Patch keyboard HID module.
tiny-pilot/ansible-role-tinypilot pull request #155
Opened 2021-11-01 17:33 UTC by jdeanwallace

The patched HID module allows a Mac to recognize the TinyPilot keyboard in pre-boot (i.e. login screen).

The [patch](https://github.com/raspberrypi/linux/commit/d7428bc26fc767942c38d74b80299bcd4f01e7cb) is already included kernel versions [`>= 5.15`](https://github.com/raspberrypi/linux/commits/rpi-5.15.y/drivers/usb/gadget/function). However, the latest LTS kernel is version `5.10`. This PR installs the patched HID module on kernel versions `>=5.10` and `<5.15`.

This PR does the following:
1. Downloads and installs the patched `usb_f_hid.ko` module ([here](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L68-L73)).
2. Updates the USB gadget initializer by adding an additional `no_out_endpoint` HID function ([here](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L75-L84)). This HID function is only supported after the patch. We cannot add this function without the patched module.

Fixes #151

2021-11-01 17:36 UTC, jdeanwallace commented
@mtlynch can you please upload the [compiled `usb_f_hid.ko` file](https://storage.googleapis.com/jason-tinypilotkvm/usb_f_hid.ko) to a GCS bucket and make is publicly accessible?

2021-11-01 22:08 UTC, mtlynch commented
Doesn't 5.13 have the fix? We don't want to mess with the kernel if we don't have to, so I want to be as conservative as possible in patching the module if we don't need to.

I'm not following the logic for using 5.10 as the min version. Doesn't every kernel version before 5.13 need this fix? We're not guaranteed that the user is running the latest Raspbian.

Also, for situations where we're applying a workaround, I'd like to go heavy on code comments and clear naming. We should aim for the reader to understand the context of the workaround without digging into `git blame` and finding associated issues and PRs (though it's good to link to the associated issues).

>@mtlynch can you please upload the compiled usb_f_hid.ko file to a GCS bucket and make is publicly accessible?

Can you share a bash script that compiles it? I want to store the script with the .ko so that we can reproduce it if necessary. The end-user won't see the script. It will just sit in the bucket folder next to the .ko.

2021-11-02 13:04 UTC, jdeanwallace commented
> Doesn't 5.13 have the fix?

Not from what I can see. The fix adds support for an additional [`no_out_endpoint` function here](https://github.com/raspberrypi/linux/blob/d7428bc26fc767942c38d74b80299bcd4f01e7cb/drivers/usb/gadget/function/u_hid.h#L23).

* Version [5.13 doesn't have it](https://github.com/raspberrypi/linux/blob/rpi-5.13.y/drivers/usb/gadget/function/u_hid.h).
* Version [5.14 doesn't have it](https://github.com/raspberrypi/linux/blob/rpi-5.14.y/drivers/usb/gadget/function/u_hid.h).
* Version [5.15 does have it](https://github.com/raspberrypi/linux/blob/rpi-5.15.y/drivers/usb/gadget/function/u_hid.h#L23).

---

> I'm not following the logic for using 5.10 as the min version. Doesn't every kernel version before 5.13 need this fix? We're not guaranteed that the user is running the latest Raspbian.

I used 5.10 as the min version because it is latest LTS version that I tested on. I wasn't sure how far back the patch diff would be successfully applied to the file. I didn't think it was that important to be backwards compatible because I thought "hey, if you want the latest features, then be on the latest version".

I just tried to apply the patch diff to earliest kernel version where the patched files exist (i.e. [version 3.19](https://github.com/raspberrypi/linux/blob/rpi-3.19.y/drivers/usb/gadget/function/u_hid.h)), but the patch did no apply successfully. From which kernel version should I start applying this patch? I suggest we only support from the earliest kernel version that TinyPilot Pro was first shipped with.

---

> Also, for situations where we're applying a workaround, I'd like to go heavy on code comments and clear naming. We should aim for the reader to understand the context of the workaround without digging into git blame and finding associated issues and PRs (though it's good to link to the associated issues).

Okay cool, I'll add more explanation to the code that applies the workaround.

---

> Can you share a bash script that compiles it?

Sure, you can run the following script on the device as root:

```bash
#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Install dependencies.
apt-get install git bc bison flex libssl-dev make libc6-dev libncurses5-dev -y

# Clone repo.
BUILD_DIR="$(mktemp --directory)"
pushd "${BUILD_DIR}"
git clone --depth=1 --branch rpi-5.10.y https://github.com/raspberrypi/linux
pushd linux

# Apply patch.
curl https://github.com/raspberrypi/linux/commit/d7428bc26fc767942c38d74b80299bcd4f01e7cb.patch \
  --output fix.patch
git apply fix.patch

# Generate config.
KERNEL=kernel7l
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig

# Build module.
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules_prepare
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- M=drivers/usb/gadget/function

# Install module.
cp ./drivers/usb/gadget/function/usb_f_hid.ko \
  /lib/modules/$(uname -r)/kernel/drivers/usb/gadget/function/

```

2021-11-02 16:02 UTC, mtlynch commented
@jdeanwallace - Thanks for the explanation. Good points! I agree with you on applying it only to >= 5.10 through < 5.15.

The script you shared clones only the the `rpi-5.10.y` branch. We want `rpi-5.15.y`, though, right?

2021-11-03 15:48 UTC, jdeanwallace commented
> The script you shared clones only the the rpi-5.10.y branch. We want rpi-5.15.y, though, right?

Bizarrely, that doesn't work 🤔. The module builds fine, but after the install & reboot, the [`init-usb-gadget`](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/files/init-usb-gadget) script in unable to create the `/sys/kernel/config/usb_gadget/g1/functions/hid.keyboard` directory. Full output below:

```bash
/opt/tinypilot-privileged/init-usb-gadget
+ set -u
+ modprobe libcomposite
+ cd /sys/kernel/config/usb_gadget/
+ mkdir -p g1
+ cd g1
+ echo 0x1d6b
+ echo 0x0104
+ echo 0x0100
+ echo 0x0200
+ STRINGS_DIR=strings/0x409
+ mkdir -p strings/0x409
+ echo 6b65796d696d6570690
+ echo tinypilot
+ echo 'Multifunction USB Device'
+ KEYBOARD_FUNCTIONS_DIR=functions/hid.keyboard
+ mkdir -p functions/hid.keyboard
mkdir: cannot create directory 'functions/hid.keyboard': No such file or directory
```
I'm actually unable to create any file or directory inside `/sys/kernel/config/usb_gadget/g1/functions/` 🤔 

If I run the script with the `rpi-5.10.y` branch, then it works again after reboot.

2021-11-03 18:42 UTC, mtlynch commented
Oh, gotcha. I missed that we were applying a patch too. I'll create a public github repo for this and then check in the compiled .ko.

2021-11-03 22:45 UTC, mtlynch commented
Okay, here's the public version:

https://github.com/tiny-pilot/hid-backport/raw/master/bin/usb_f_hid.ko

The repo itself is obviously at:

https://github.com/tiny-pilot/hid-backport

Can you verify that my `usb_f_hid.ko` file works the same as the version you compiled?

2021-11-04 14:15 UTC, jdeanwallace commented
Thanks!

> Can you verify that my `usb_f_hid.ko` file works the same as the version you compiled?

Yes, it works!

2021-11-04 14:37 UTC, mtlynch reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155)* status: 0 of 1 LGTMs obtained

___
*[tasks/install_usb_gadget.yml, line 77 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MnfN05c1sKQ260CEjbJ:-MnfN05c1sKQ260CEjbK:b-doad70) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L77)):*
> ```YAML
> - name: patch usb-gadget initializer
>   ansible.builtin.lineinfile:
>     path: "{{ tinypilot_privileged_dir }}/init-usb-gadget"
> ```

We're overwriting the entire `init-usb-gadget` file in the "copy usb-gadget initializer" so I think it's fine to just update in that file directly instead of copying it and making a really delicate tweak to a particular line. Does anything bad happen if we include the line on < 5.10?


<!-- Sent from Reviewable.io -->

2021-11-04 20:57 UTC, mtlynch reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155)* status: 0 of 1 LGTMs obtained

___
*[tasks/install_usb_gadget.yml, line 69 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MngigT-3gO3wTZ_tTlW:-MngigT01dYqbobr9hWM:b-cbfhom) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L69)):*
> ```YAML
> 
> - name: patch HID module
>   get_url:
> ```

I'm realizing we'll want something to indicate that we've applied the backport already, otherwise we'll slow down the role by downloading and replacing this file every time.

My thought is that we save a file like `/home/tinypilot/.applied-hid-workaround` on change and skip this play if the file already exists?

We do something sort of similar in uStreamer:

https://github.com/tiny-pilot/ansible-role-ustreamer/blob/f09f0f9b0da4a840d8b588435b0a57cfa27d4319/tasks/main.yml#L100


<!-- Sent from Reviewable.io -->

2021-11-05 15:06 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155)* status: 0 of 1 LGTMs obtained

___
*[tasks/install_usb_gadget.yml, line 69 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MngigT-3gO3wTZ_tTlW:-MnkT6X959V8DgzOfXiy:bwhlc4o) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L69)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I'm realizing we'll want something to indicate that we've applied the backport already, otherwise we'll slow down the role by downloading and replacing this file every time.

My thought is that we save a file like `/home/tinypilot/.applied-hid-workaround` on change and skip this play if the file already exists?

We do something sort of similar in uStreamer:

https://github.com/tiny-pilot/ansible-role-ustreamer/blob/f09f0f9b0da4a840d8b588435b0a57cfa27d4319/tasks/main.yml#L100
</blockquote></details>

Good point. I see that [`get_url` has a `checksum` parameter](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-checksum) that will only download the file if the local file doesn't exist or has a different checksum. I've added that here: https://github.com/tiny-pilot/ansible-role-tinypilot/blob/81465175329e6ee8eb55a730c3f3232f6c3165a2/tasks/install_usb_gadget.yml#L76
___
*[tasks/install_usb_gadget.yml, line 77 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MnfN05c1sKQ260CEjbJ:-MnkVtKb0BVaKf6vSePk:b-kphsy0) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L77)):*
> Does anything bad happen if we include the line on < 5.10?

If the USB gadget doesn't support the endpoint then it won't allow us to write to the file. However, it seems like you can easily determine if the gadget supports `/no_out_endpoint` by just checking if the file exists. The gadget only supports the endpoints that exist on the filesystem.

I've added code to `init-usb-gadget` that only enables the feature if the file exists:
https://github.com/tiny-pilot/ansible-role-tinypilot/blob/81465175329e6ee8eb55a730c3f3232f6c3165a2/files/init-usb-gadget#L75-L78


<!-- Sent from Reviewable.io -->

2021-11-05 15:11 UTC, mtlynch requested changes
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155)* status: 0 of 1 LGTMs obtained

___
*[tasks/install_usb_gadget.yml, line 69 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MngigT-3gO3wTZ_tTlW:-MnkdUqb8DsNxtONGuBi:b51wgrl) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b7e7f89983c27bea88452d8748b96fbb2a0db8f7/tasks/install_usb_gadget.yml#L69)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

Good point. I see that [`get_url` has a `checksum` parameter](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-checksum) that will only download the file if the local file doesn't exist or has a different checksum. I've added that here: https://github.com/tiny-pilot/ansible-role-tinypilot/blob/81465175329e6ee8eb55a730c3f3232f6c3165a2/tasks/install_usb_gadget.yml#L76
</blockquote></details>

Oh, nice! Very clean.
___
*[tasks/install_usb_gadget.yml, line 77 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MnkdklX9j6m6THnQ13p:-MnkdklX9j6m6THnQ13q:b-7ktye2) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/81465175329e6ee8eb55a730c3f3232f6c3165a2/tasks/install_usb_gadget.yml#L77)):*
> ```YAML
>     mode: '0664'
>     checksum: sha256:45f9c885e8b0e1d2fdaf4aec2179a38ad9a1c76c71f44c997c99a865fdfe72d7
>   when: ansible_kernel is version('5.15', '<') and ansible_kernel is version('5.10', '>=')
> ```

Do we need to add a handler to reload the kernel module if we change it?


<!-- Sent from Reviewable.io -->

2021-11-08 15:29 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155)* status: 0 of 1 LGTMs obtained

___
*[tasks/install_usb_gadget.yml, line 77 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MnkdklX9j6m6THnQ13p:-Mo-5gKt0qNjzMAbtCeO:bdim9il) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/81465175329e6ee8eb55a730c3f3232f6c3165a2/tasks/install_usb_gadget.yml#L77)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Do we need to add a handler to reload the kernel module if we change it?
</blockquote></details>

Yes, I was relying on the module to be reloaded after a reboot. However, the reboot happens outside of ansible.

I'm trying to add a handler to reload the module using `modprobe [-r] usb_f_hid`, but it's not always successful because it depends on the state of the `usb-gadget` service (i.e. is the gadget in use).

The safest/simplest option is the `reboot` because it can never fail.

I'll try add extra logic to ansible task to ensure a smooth kernel module reload.


<!-- Sent from Reviewable.io -->

2021-11-09 13:48 UTC, jdeanwallace reviewed
I've managed to safely patch and reload the `usb_f_hid` module.

Just a note on something strange that happens when I attempt to undo the patch. Before the module is patched, it is easy to unload (`modprobe --remove usb_f_hid`) and load (`modprobe usb_f_hid`) the module, as long as the `usb-gadget` is removed. However, after the module is patched I am unable to unload the module. The only way I can reload a new module is to reboot the device. I received the following error message when running `modprobe --remove usb_f_hid` while the patched module is loaded:

```bash
modprobe: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'usb_f_hid': Device or resource busy
```

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-:-Mo3uGvX2j7relmUpBFF:bahj2yl)* status: 0 of 1 LGTMs obtained

___
*[tasks/install_usb_gadget.yml, line 77 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/155#-MnkdklX9j6m6THnQ13p:-Mo3s-Z7D9vIGY1phkVw:b-896fix) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/81465175329e6ee8eb55a730c3f3232f6c3165a2/tasks/install_usb_gadget.yml#L77)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

Yes, I was relying on the module to be reloaded after a reboot. However, the reboot happens outside of ansible.

I'm trying to add a handler to reload the module using `modprobe [-r] usb_f_hid`, but it's not always successful because it depends on the state of the `usb-gadget` service (i.e. is the gadget in use).

The safest/simplest option is the `reboot` because it can never fail.

I'll try add extra logic to ansible task to ensure a smooth kernel module reload.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-10 13:03 UTC, merged