Install Janus Gateway and uStreamer Janus plugin
tiny-pilot/ansible-role-tinypilot pull request #191
Opened 2022-03-24 04:09 UTC by jdeanwallace

This PR allows us to install the Janus Gateway using the [`tinypilot_install_janus` variable (off by default)](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/defaults/main.yml#L19).

### Changes
1. Adds `ansible-role-janus-gateway` as a dependency ([link](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/requirements.yml#L4)).
1. Installs Janus Gateway ([link](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/tasks/main.yml#L2-L6)).
1. Patches Janus header file to allow us to compile the uStreamer Janus plugin ([link](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/tasks/ustreamer.yml#L2-L7)).
1. Create uStreamer Janus plugin config file ([link](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/templates/janus.plugin.ustreamer.jcfg.j2)).
1. Installs uStreamer Janus plugin ([link](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/tasks/ustreamer.yml#L22-L30)).
1. Upgrades uStreamer to versions `v4.13` ([link](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/vars/main.yml#L13)).

2022-03-24 04:29 UTC, jdeanwallace commented
@mtlynch I'm struggling to find the line where this PR should end. I'm ultimately trying to resolve https://github.com/tiny-pilot/ansible-role-tinypilot/issues/168, but I feel like the scope might be too broad for one PR. Based on [your comment here](https://github.com/tiny-pilot/ansible-role-tinypilot/pull/190#issuecomment-1075111861), we should bring the Janus install right into `master` instead of `experimental/h264` which is what I'm trying to do with this PR, but it's starting to look very similar to `experimental/h264` anyway.

Should I create a separate PR for the Janus-nginx config or put it all in this PR too?

2022-03-24 12:17 UTC, mtlynch requested changes
> I'm struggling to find the line where this PR should end. I'm ultimately trying to resolve #168, but I feel like the scope might be too broad for one PR. Based on your comment here, we should bring the Janus install right into master instead of experimental/h264 which is what I'm trying to do with this PR, but it's starting to look very similar to experimental/h264 anyway.

I can't think of anything left to add to `experimental/h264` at this point. The purpose of the branch was just to get a proof of concept working and give Jan something to build against for the frontend work, which we've achieved.

We don't need to productionize the `experimental/h264` branch, though. Now that we have the proof of concept, we can port everything we need to`master`.

>Should I create a separate PR for the Janus-nginx config or put it all in this PR too?

Let's do it in this PR. This PR doesn't feel excessively big, and it'd be good to pull in all of the required Janus changes in a single PR.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-:-MyvpdnH7PXXZ1l4SNFg:bsnk509)* status: 0 of 1 LGTMs obtained

___
*[defaults/main.yml, line 19 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MyvqIXmBg8gFM35bIdz:-MyvqIXmBg8gFM35bIe-:b-gxyi3n) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/defaults/main.yml#L19)):*
Can we add this comment:

>(Experimental): Install the Janus WebRTC server to enable uStreamer to stream video over H264 instead of MJPEG.
___
*[tasks/ustreamer.yml, line 4 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MyvfXsh7nz_CaI_lzEA:-MyvfXsi9MU1rdtg0uRf:b-7014vj) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/tasks/ustreamer.yml#L4)):*
> ```YAML
> # We're unable to build the uStreamer Janus plugin because an include statement
> # references the wrong file path.
> # TODO: Create a PR to patch this bug in the janus-gateway repo.
> ```

I created a bug for this. Can we reference the bug here?

https://github.com/tiny-pilot/ansible-role-tinypilot/issues/192
___
*[vars/main.yml, line 13 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MyvbATC1S8mLQyC4pZC:-MyvbATC1S8mLQyC4pZD:b-mf32ec) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/ec2a68e7c95195e41f4bda51e402ebeefff1264f/vars/main.yml#L13)):*
> ```YAML
> ustreamer_port: 8001
> ustreamer_repo: https://github.com/tiny-pilot/ustreamer.git
> ustreamer_repo_version: v4.13
> ```

Can we pin the Janus repo versions as well?


<!-- Sent from Reviewable.io -->

2022-03-30 16:16 UTC, jdeanwallace reviewed
You can enable streaming over WebRTC by specifying these additional ansible variables when running this role:
```bash
ustreamer_h264_sink: tinypilot::ustreamer::h264
ustreamer_h264_sink_mode: 777
ustreamer_h264_sink_rm: yes
ustreamer_compile_janus_plugin: yes
tinypilot_install_janus: yes
```

I used the ["Local Testing" instructions from the TinyPilot Pro repo](https://github.com/tiny-pilot/ansible-role-tinypilot-pro#local-testing) to test this role on device.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-:-MzQ_f8B8BqQbOT_vaMP:b-plljd2)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-03-30 21:42 UTC, mtlynch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-:-MzRlpNu0bZFw-cLcH1u:b-41s8zb)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[templates/tinypilot-app-settings.cfg.j2, line 6 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MzRlk9BB4XXHjs9v6Ue:-MzRlk9C7LD1ltYKNR45:bx6skg9) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/1a4767f44bf3dab0bd594bf7a9784c04ba07855d/templates/tinypilot-app-settings.cfg.j2#L6)):*
> ```Jinja
> KEYBOARD_PATH = '{{ tinypilot_keyboard_interface }}'
> MOUSE_PATH = '{{ tinypilot_mouse_interface }}'
> {% if tinypilot_install_janus and ustreamer_compile_janus_plugin and ustreamer_h264_sink != None -%}
> ```

(nit) Can we reformat to avoid exceeding 80 columns?
___
*[vars/main.yml, line 17 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MzQTchI84uApo09vA8M:-MzRkwJI36qTZ3GMTaP8:b-pidf1o) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/1a4767f44bf3dab0bd594bf7a9784c04ba07855d/vars/main.yml#L17)):*
Can we add a comment here this just saying that they don't affect the Janus role?

>We can make an effort to add these variables to ansible-role-janus-gateway, but the repo currently makes use variables that are nested dictionaries/lists. Ansible overrides variables at the first level. 

Huh, weird. That seems like a design flaw, but I wonder if we're missing something, and there's a clean way to do what we want. The maintainer used to work for Ansible, so I'd expect her to know best practices, but I can't figure out the logic here. I was hoping she'd be more interested in accepting our changes upstream, and I submitted a trivial fix last week but she hasn't responded.


<!-- Sent from Reviewable.io -->

2022-03-31 11:17 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[templates/tinypilot-app-settings.cfg.j2, line 6 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MzRlk9BB4XXHjs9v6Ue:-MzUc40U0s1hl_vA9esr:b-896fix) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/1a4767f44bf3dab0bd594bf7a9784c04ba07855d/templates/tinypilot-app-settings.cfg.j2#L6)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

(nit) Can we reformat to avoid exceeding 80 columns?
</blockquote></details>

Done.
___
*[vars/main.yml, line 17 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/191#-MzQTchI84uApo09vA8M:-MzUe-6a7dEPwf-B-9lN:bu4s5l8) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/1a4767f44bf3dab0bd594bf7a9784c04ba07855d/vars/main.yml#L17)):*
> Can we add a comment here this just saying that they don't affect the Janus role?
 
Done.


<!-- Sent from Reviewable.io -->

2022-03-31 11:19 UTC, merged