Install pre-built Janus Debian package
tiny-pilot/ansible-role-tinypilot pull request #200
Opened 2022-05-20 13:12 UTC by jdeanwallace

Resolves #199

2022-05-24 15:05 UTC, mtlynch requested changes
> On the device, run the follow commands to enable H264 streaming:

Won't this install it from source with the Ansible role rather than with the new Debian package?

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-:-N2q_Acc3kONwSMBgcH-:b-3apotn)* status: 0 of 1 LGTMs obtained

___
*[`requirements.yml` line 4 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-N2ljMmR2SL-Z78wXIlr:-N2qL1v271Wf--E2-98a:bh848jx) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/63996cfd1d9cabb3a26d9c1a3dcea20ee3b24a55/requirements.yml#L4)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

I'm reluctant to add cleanup code because it's an eyesore and it'll have to live in our codebase forever.

We don't have a great way of dealing with unused dependencies (even for our pip requirements), we just always add and never remove.

So leaving an unused `/opt/tinypilot-updater/ansible-role-janus-gateway` directory on disk doesn't seem like a big deal either.
</blockquote></details>

Yeah, I think leaving the old role is fine. I believe it's less than 1 MB of data, so I'm not too worried about leaving it behind, especially since it will only be on systems that tried the experimental opt-in.
___
*[`tasks/janus.yml` line 8 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-N2q_f-_-wgXwetFNevM:-N2q_f-_-wgXwetFNevN:b-cddbye) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/1ace7f946858c25cabdfbb4f819685613751c8d5/tasks/janus.yml#L8)):*
> ```YAML
>     # conflicting dependencies. This does not install Janus on every provision.
>     # https://github.com/tiny-pilot/janus-debian/blob/1.0.1/Dockerfile#L172
>     force: yes
> ```

Is this just for people who installed the experimental version? If so, I'd rather just update our [install instructions](https://tinypilotkvm.com/blog/whats-new-in-2022-05#enabling-h264-video) to add `sudo apt-get remove -y libwebsockets ...` at the  top.


<!-- Sent from Reviewable.io -->

2022-05-24 15:18 UTC, jdeanwallace reviewed
> Won't this install it from source with the Ansible role rather than with the new Debian package?

Yes, sorry I thought that's what @jotaen4tinypilot was looking for.

If not, this is how you can run re-provison a TinyPilot device using the current branch:

1. Install the latest version TinyPilot on a hobbyist device. You can do this by flashing an SD card with the latest build or to install it via the `quick-install` script.
2. On your dev machine, pull down the latest changes for this branch.
3. On your dev machine, follow the [Local Testing](https://github.com/tiny-pilot/ansible-role-tinypilot-pro#local-testing) instructions for a hobbyist device.
    * In order to enable H264 on the device, use the following command to generate the appropriate ansible playbook:
        ```bash
        TINYPILOT_PLAYBOOK=$(mktemp)
        echo "- hosts: all
          become: true
          become_method: sudo
          roles:
            - role: ${PWD}
              vars:
                ustreamer_h264_sink: tinypilot::ustreamer::h264
                ustreamer_h264_sink_mode: 777
                ustreamer_h264_sink_rm: yes
                ustreamer_compile_janus_plugin: yes
                tinypilot_install_janus: yes" > "${TINYPILOT_PLAYBOOK}"
        ```
4. Now you should have the Janus systemd service running and WebRTC enabled on the frontend.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-:-N2qbIAa7x-G66lMIMqk:btqg9lx)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-05-25 13:25 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200)* status: 0 of 1 LGTMs obtained

___
*[`tasks/janus.yml` line 8 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-N2q_f-_-wgXwetFNevM:-N2vH5yY--4KSrh0ZEUO:beydmza) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/1ace7f946858c25cabdfbb4f819685613751c8d5/tasks/janus.yml#L8)):*
> Is this just for people who installed the experimental version?

Yes.

Done, thanks I've updated the install instructions here: https://github.com/tiny-pilot/tinypilotkvm.com/pull/734


<!-- Sent from Reviewable.io -->

2022-05-26 10:33 UTC, jotaen4tinypilot approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (Tested again on device.)

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-:-N2zt_rX9efiT8xVAIss:bs7n4e4)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`tasks/ustreamer.yml` line 16 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-N2ztnH70MUC6w0iE-_Y:-N2ztnH70MUC6w0iE-_Z:b6uxkus) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/63996cfd1d9cabb3a26d9c1a3dcea20ee3b24a55/tasks/ustreamer.yml#L16)):*
> ```YAML
>   template:
>     src: janus.plugin.ustreamer.jcfg.j2
>     dest: "{{ janus_conf_dir }}/janus.plugin.ustreamer.jcfg"
> ```

Two question here, just for my own understanding:

- Had `janus_conf_dir` been defined anywhere previously? I.e., we don’t have to delete any definition now that we removed the last usage of the variable?
- `janus_install_dir` is [now defined by us explicitly](https://github.com/tiny-pilot/ansible-role-tinypilot/pull/200/files#diff-b8e57d5bc17b5679065938c3a8fd9be95bf3e5b1b6c80c1e4bee652492ae740fR18), but [we were already using it before](https://github.com/tiny-pilot/ansible-role-tinypilot/pull/200/files#diff-3e9ac118f46e7a365f2191a7417100e680dfa4bf9ba09a163f79593ef0b11a32L26). This is obviously not a problem, right?

Are these some sort of magic Ansible variables? ([I couldn’t find anything about it in the docs, though.](https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html))


<!-- Sent from Reviewable.io -->

2022-05-26 12:08 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`tasks/ustreamer.yml` line 16 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/200#-N2ztnH70MUC6w0iE-_Y:-N3-Blxg4Gl0nTA-CQxJ:b29si6a) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/63996cfd1d9cabb3a26d9c1a3dcea20ee3b24a55/tasks/ustreamer.yml#L16)):*
> * Had `janus_conf_dir` been defined anywhere previously? I.e., we don’t have to delete any definition now that we removed the last usage of the variable?
> * `janus_install_dir` is now defined by us explicitly, but we were already using it before. This is obviously not a problem, right?

Both `janus_conf_dir` and `janus_install_dir` were defined in [`ansible-role-janus-gateway`](https://github.com/tiny-pilot/ansible-role-janus-gateway/blob/a22e9ef998b00ca65b1574c9266a0232d791b577/defaults/main.yml#L24-L25), so when we import the role we're also able to reference the variables it defines.

From the [docs for the `import_role` module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_role_module.html#notes):
> Since Ansible 2.7 variables defined in `vars` and `defaults` for the role are exposed to the play at playbook parsing time. Due to this, these variables will be accessible to roles and tasks executed before the location of the `ansible.builtin.import_role` task.

That's also why it's important to namespace variables (with a prefix like `tinypilot_`) because it's easy to have variable naming collisions between roles.

So to answer your questions, we need explicitly define `janus_install_dir` because we're no longer importing the `ansible-role-janus-gateway` role.


<!-- Sent from Reviewable.io -->

2022-05-26 12:09 UTC, merged