Fix TinyPilot version check in `collect-debug-logs` script.
tiny-pilot/ansible-role-tinypilot pull request #217
Opened 2022-08-18 13:46 UTC by jdeanwallace

2022-08-18 13:55 UTC, jdeanwallace commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/217)

⏳ @jotaen4tinypilot please review this Pull Request

2022-08-18 14:01 UTC, jdeanwallace commented
@jotaen4tinypilot Sorry, this is a change that could probably be merged into `master` instead. Let me rebase.

2022-08-18 14:13 UTC, jdeanwallace commented
@jotaen4tinypilot Okay done, ready for review again.

2022-08-19 15:22 UTC, jotaen4tinypilot requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/217)


<img src="https://codeapprove.com/external/github-stamp-allbg.png" width="159" alt="Approved on CodeApprove" />
✔️ Approved (1 unresolved comments)

Good spot! 🕵️

We only need the git fallback for the transition period, until the update overhaul is rolled out, right? In this case, should we already file a follow-up ticket, so that we don’t forget to clean it up?

<hr />

In: **files/collect-debug-logs**:

```
> Line 69
pushd /opt/tinypilot > /dev/null || exit
```
Just curious, why do we introduce the `|| exit` here?


<hr />

👀 @jdeanwallace it's your turn please take a look

2022-08-19 15:56 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/217)



<hr />

In: **Discussion**
Ah yeah, now that you mention it we also need to rid of using the TinyPilot repo all together. I've filed this issue to track: https://github.com/tiny-pilot/ansible-role-tinypilot/issues/218

<hr />

In: **files/collect-debug-logs**:

```
> Line 69
pushd /opt/tinypilot > /dev/null || exit
```
It's a [check enforced by `shellcheck`](https://app.circleci.com/pipelines/github/tiny-pilot/ansible-role-tinypilot/496/workflows/d3370f2f-f5de-4b4b-8422-13d88195559c/jobs/1098?invite=true#step-103-6). Shellcheck wants us to either `set -e` for the entire file (which we don't do) or anticipate failing commands with `|| exit`.

I wanted to use `set -e` globally, but it caused other parts of the script to exit prematurely while testing.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2022-08-22 13:27 UTC, merged