Add support for uStreamer 5.x on Bullseye
tiny-pilot/ansible-role-tinypilot pull request #222
Opened 2022-09-23 15:56 UTC by mtlynch

2022-09-27 15:29 UTC, mtlynch commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/222)

⏳ @jdeanwallace please review this Pull Request

2022-09-28 14:09 UTC, jdeanwallace requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/222)


<img src="https://codeapprove.com/external/github-stamp-allbg.png" width="159" alt="Approved on CodeApprove" />
✔️ Approved (3 unresolved comments)

<hr />

In: **Discussion**
I haven't tested this on device, but I'm curious to know how you tested this on device now that our update overhaul makes that less fun?

<hr />

In: **tasks/ustreamer.yml**:

```
> Line 8
    ustreamer_repo_version: "{{ ustreamer_repo_version_modern }}"
```
We always override the `ustreamer_repo_version` which means that any version specified via `ustreamer_repo_version` (as extra playbook vars) will not be honored. Is that intended?

<hr />

In: **tasks/ustreamer.yml**:

```
> Line 19
    ustreamer_repo_version: "{{ ustreamer_repo_version }}"
```
I'm not 100% sure, but I think we can omit setting this role variable here because `ansible-role-ustreamer` will pick up the `ustreamer_repo_version` value that was set via the previous `set_fact` task 🤔 ([source](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence))


<hr />

👀 @mtlynch it's your turn please take a look

2022-09-28 22:38 UTC, mtlynch reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/222)



<hr />

In: **Discussion**
It's the same process as before since we still allow git-based installation of tinypilot in the Ansible role. You can't install on top of an existing new-style install (it will complain that /opt/tinypilot is not a git repo), but you can install fine on a clean Raspbian OS.

<hr />

In: **tasks/ustreamer.yml**:
Ah, you're right. Removed.

<hr />

In: **tasks/ustreamer.yml**:

```
> Line 8
    ustreamer_repo_version: "{{ ustreamer_repo_version_modern }}"
```
There aren't really cases where I'd expect the user to override, but maybe it will be useful for development to have that functionality, so I added conditions.

2022-09-28 22:38 UTC, jdeanwallace approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/222)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2022-09-29 09:53 UTC, merged